---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CF template to setup cognito user pool'
Parameters:
  Environment:
    Type: String
    Default: 'dev'
    Description: 'The name of the environment to deply [dev, qa, stage, prod]'
    AllowedPattern : '^|dev|$'
  
Resources:
  SNSRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: 'CognitoSNSRoletest'
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: 
              Service: 
                - "cognito-idp.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "CognitoSNSPolicy"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: "sns:publish"
                Resource: "*"
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: 'UserPooltest'
      AdminCreateUserConfig: 
        AllowAdminCreateUserOnly: true
        UnusedAccountValidityDays: 30
        
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
        - phone_number
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: tenant_id
          StringAttributeConstraints:
            MaxLength: 36
            MinLength: 36
          Required: false
      MfaConfiguration: OPTIONAL
      UserPoolTags:
        Name: userpool-test-email
      SmsConfiguration:
        ExternalId: userpool-dev
        SnsCallerArn: !GetAtt SNSRole.Arn
  
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: 'UserPoolClienttest'
      GenerateSecret: false
      RefreshTokenValidity: 30
      UserPoolId: 
        Ref: UserPool
      ReadAttributes:
        - address
        - birthdate
        - email
        - email_verified
        - family_name
        - gender
        - given_name
        - locale
        - middle_name
        - name
        - nickname
        - phone_number
        - phone_number_verified
        - picture
        - preferred_username
        - profile
        - zoneinfo
        - updated_at
        - website
      WriteAttributes:
        - address
        - birthdate
        - email
        - family_name
        - gender
        - given_name
        - locale
        - middle_name
        - name
        - nickname
        - phone_number
        - picture
        - preferred_username
        - profile
        - zoneinfo
        - updated_at
        - website
  CognitoUserPoolId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/EnvVars/dev/CognitoUserPoolId'
      Type: String
      Value: !GetAtt UserPool.Arn
      Description: "Id of cognito userpool"
  CognitoUserPoolAppId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/EnvVars/dev/CognitoUserPoolAppId'
      Type: String
      Value: !Ref UserPoolClient
      Description: "Id of cognito userpool client"

Outputs:
  CognitoUserPoolId:
    Description: "ARN of cognito userpool"
    Value: !GetAtt UserPool.Arn
  CognitoUserPoolAppId:
    Description: "Id of cognito userpool client"
    Value: 
      Ref: UserPoolClient